package com.example.model

enum class AppLanguage {
    ENGLISH,
    AMHARIC
}

object Translation {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> englishStrings[key] ?: key
            AppLanguage.AMHARIC -> amharicStrings[key] ?: (englishStrings[key] ?: key)
        }
    }

    private val englishStrings = mapOf(
        "app_tagline" to "Elite Gift Selling Platform",
        "welcome" to "Welcome to",
        "teke_promo" to "Teke Man Promotion",
        "home" to "Home",
        "categories" to "Categories",
        "favorites" to "Favorites",
        "cart" to "Cart",
        "profile" to "Profile",
        "search_hint" to "Search exclusive gifts...",
        "special_offers" to "Special Offers",
        "popular" to "Popular",
        "buy_now" to "Buy Now",
        "add_to_cart" to "Add to Cart",
        "added_to_cart" to "Added to Cart!",
        "added_to_fav" to "Added to Favorites!",
        "removed_from_fav" to "Removed from Favorites!",
        "empty_cart" to "Your cart is empty",
        "empty_fav" to "No favorite items yet",
        "empty_desc" to "Browse our premium catalogue to add items here.",
        "order_now" to "Order Now",
        "total" to "Total",
        "checkout" to "Checkout",
        "subtotal" to "Subtotal",
        "shipping" to "Shipping (Luxury Delivery)",
        "free" to "Free",
        "currency" to "ETB",
        "languages" to "Languages",
        "themes" to "Themes",
        "theme_light" to "Light Elegant Theme",
        "theme_dark" to "Dark Obsidian Theme",
        "theme_auto" to "System Adaptive",
        "contact_us" to "Contact Us",
        "contacts_desc" to "Direct communication with our premier concierge service.",
        "order_confirm_title" to "Confirm Luxury Order",
        "order_confirm_desc" to "To finalize your bespoke order, we will connect you directly with our premier sales agent via phone call.",
        "order_confirm_btn" to "Initiate Phone Call",
        "cancel" to "Cancel",
        "items" to "items",
        "specs" to "Bespoke Details",
        "reviews" to "Reviews",
        "rating" to "Rating",
        "related_products" to "Exquisite Accompanying Sets",
        "delivery_info" to "Elite 2-Hour Delivery in Addis Ababa, and express shipping nationwide.",
        "gift_wrapping" to "Complimentary Premium Wooden Case & Satin Ribbon wrapping.",
        "order_history" to "Order History",
        "about_teke" to "About Teke Man Promotion",
        "about_desc" to "Teke Man Promotion is Addis Ababa's foremost elite gifting service. We specialize in custom luxury chocolate arrangements, pristine rose boxes, elegant wedding accessories, corporate bundles, and breathtaking birthday celebrations.",
        "tap_to_copy" to "Tap to copy",
        "copied" to "Copied to clipboard!",
        "tiktok" to "Tiktok Channel",
        "telegram" to "Telegram Boutique",
        "call_agent" to "Call Premium Agent",
        "phone_title" to "Phone Enquiries",
        "gift_options" to "Customization & Ribbon wrapping"
    )

    private val amharicStrings = mapOf(
        "app_tagline" to "ልዩ እና የቅንጦት ስጦታዎች መሸጫ",
        "welcome" to "እንኳን ወደ",
        "teke_promo" to "ተኬ ማን ፕሮሞሽን በደህና መጡ",
        "home" to "ቤት",
        "categories" to "ምድቦች",
        "favorites" to "ተወዳጆች",
        "cart" to "ጋሪ",
        "profile" to "መገለጫ",
        "search_hint" to "ልዩ ስጦታዎችን ይፈልጉ...",
        "special_offers" to "ልዩ ቅናሾች",
        "popular" to "ተወዳጅ ምርቶች",
        "buy_now" to "አሁኑኑ ይግዙ",
        "add_to_cart" to "ጋሪ ውስጥ አስገባ",
        "added_to_cart" to "ጋሪ ውስጥ ተጨምሯል!",
        "added_to_fav" to "ከተወዳጆች ጋር ተደምሯል!",
        "removed_from_fav" to "ከተወዳጆች ተቀንሷል!",
        "empty_cart" to "የስጦታ ጋሪዎ ባዶ ነው",
        "empty_fav" to "ምንም የተወደዱ ስጦታዎች የሉም",
        "empty_desc" to "እባክዎ የእኛን ምርጥ ምርቶች ጎብኝተው እዚህ ይጨምሩ።",
        "order_now" to "አሁኑኑ ይዘዙ",
        "total" to "አጠቃላይ ድምር",
        "checkout" to "ትዕዛዝ ማረጋገጫ",
        "subtotal" to "ንዑስ ድምር",
        "shipping" to "የቅንጦት ማድረሻ አገልግሎት",
        "free" to "በነጻ",
        "currency" to "ብር",
        "languages" to "ቋንቋዎች",
        "themes" to "ገጽታዎች",
        "theme_light" to "ብርሃን ገጽታ",
        "theme_dark" to "ጨለማ ገጽታ",
        "theme_auto" to "ራስ-ሰር ገጽታ",
        "contact_us" to "ያግኙን",
        "contacts_desc" to "ከፍተኛ ደረጃ ካለው የደንበኞች አገልግሎታችን ጋር ቀጥታ ግንኙነት።",
        "order_confirm_title" to "የቅንጦት ትዕዛዝ ማረጋገጫ",
        "order_confirm_desc" to "ትዕዛዝዎን ለማጠናቀቅ፣ በቀጥታ በስልክ ጥሪ ከዋና የሽያጭ ወኪላችን ጋር እናገናኝዎታለን።",
        "order_confirm_btn" to "በስልክ ይደውሉ",
        "cancel" to "ይቅር",
        "items" to "ምርቶች",
        "specs" to "ልዩ መግለጫዎች",
        "reviews" to "ግምገማዎች",
        "rating" to "ደረጃ",
        "related_products" to "ተጨማሪ ተዛማጅ ስጦታዎች",
        "delivery_info" to "በአዲስ አበባ ውስጥ የ 2 ሰዓት ፈጣን የቤት አቅርቦት እና በሀገር አቀፍ ደረጃ ፈጣን ጭነት።",
        "gift_wrapping" to "ነጻ የፕሪሚየም የእንጨት ሳጥን እና የሐር ጥብጣብ ስጦታ መጠቅለያ።",
        "order_history" to "የቀድሞ ትዕዛዞች",
        "about_teke" to "ስለ ተኬ ማን ፕሮሞሽን",
        "about_desc" to "ተኬ ማን ፕሮሞሽን በአዲስ አበባ ቀዳሚው የቅንጦት ስጦታ አቅራቢ ነው። እኛ በልዩ ቸኮሌቶች፣ ጽጌረዳዎች፣ የሰርግ መለዋወጫዎች፣ የድርጅት ጥቅሎች እና አስደናቂ ልደት ዝግጅቶች ላይ ልዩ ባለሙያ ነን።",
        "tap_to_copy" to "ለመቅዳት ይንኩ",
        "copied" to "ኮፒ ተደርጓል!",
        "tiktok" to "ቲክቶክ ቻናል",
        "telegram" to "ቴሌግራም ቡቲክ",
        "call_agent" to "ለፕሪሚየም ወኪል ይደውሉ",
        "phone_title" to "የስልክ ጥያቄዎች",
        "gift_options" to "ልዩ ምርጫዎች እና መጠቅለያ"
    )
}
